INFO     root:read_data.py:23 读取的yaml文件数据：
{'env': {'host': 'http://121.36.194.128:8000/'}, 'dataBase': {'host': '121.36.194.128', 'port': 3306, 'username': 'root', 'password': 123456, 'basename': 'forApiTest'}}
DEBUG    urllib3.connectionpool:connectionpool.py:227 Starting new HTTP connection (1): 121.36.194.128:8000
DEBUG    urllib3.connectionpool:connectionpool.py:452 http://121.36.194.128:8000 "GET /count?username=wrfwrf HTTP/1.1" 301 0
DEBUG    urllib3.connectionpool:connectionpool.py:452 http://121.36.194.128:8000 "GET /count/?username=wrfwrf HTTP/1.1" 200 41
INFO     root:api_requests.py:44 请求参数是：http://121.36.194.128:8000/count/?username=wrfwrf
INFO     root:api_requests.py:45 响应数据是：{'code': 200, 'count': 1, 'errmsg': 'ok'}
INFO     root:assert_contrast.py:21 进行验证data：
预期返回：{"count": "@select username from tb_users where id = 11@", "errmsg": "ok"}			实际返回：{"code": 200, "count": 1, "errmsg": "ok"}
WARNING  root:assert_contrast.py:52 断言失败：